sudo: required
services:
  - docker
  - mongodb
language: node_js # latest stable Node.js release
node_js:
  # - lts/* #latest LTS Node.js release
  - 12
branches:
  only:
    - cicd
    # - /^greenkeeper/.*$/
cache:
  directories:
    - node_modules
  # yarn: true
env:
  global:
    - ACCESS_TOKEN_SECRET=chnirt1803
    # - DOCKER_USERNAME=chnirt
    # - DOCKER_PASSWORD=12345678
before_install:
  # - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  # - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - npm i
  - npm rebuild bcrypt --update-binary
  - npm i -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
stages:
  # - build docker image
  - Unit Tests
  - E2e Tests
  - Coverage Tests
  # - UI Tests
  # - Deploy
jobs:
  include:
    # - stage: build docker image
    #   script:
    #     - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    #     - docker build -t travis-ci-build-stages-demo .
    #     - docker images
    #     - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/travis-ci-build-stages-demo
    #     - docker push $DOCKER_USERNAME/travis-ci-build-stages-demo
    - stage: Unit Tests
      script:
        - npm run gen
        - npm run test
    - stage: E2e Tests
      script:
        - npm run gen
        - npm run test:e2e
    - stage: Coverage Tests
      script:
        - npm run gen
        - npm run test:cov
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
